/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alchivosocket;

import Trabajo.ClienteSocket;
import com.placeholder.PlaceHolder;

/**
 *
 * @author Asus
 */
public class InterfaceLoginArchivos extends javax.swing.JFrame {
    private PlaceHolder holder;
    private ClienteSocket cs;
    private String ruta;
    /**
     * Creates new form InterfaceLoginArchivos
     */
    public InterfaceLoginArchivos() {
        
        initComponents();
        
        holder=new PlaceHolder(jTextfieldLoginNombre, "Ingrese su usuario o ID");
       jPasswordFieldLoginPass.setEchoChar((char)0);
        holder=new PlaceHolder(jPasswordFieldLoginPass, "Ingrese su contraseña personal");
        jPanelManejoArchivos.setVisible(false);
        jTabbedPane.remove(jPanelCrearUsuario);
        jTabbedPane.remove(jPanelManejoArchivos);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelLogin = new javax.swing.JPanel();
        jTextfieldLoginNombre = new javax.swing.JTextField();
        jPasswordFieldLoginPass = new javax.swing.JPasswordField();
        jCheckBoxLoginPass = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanelManejoArchivos = new javax.swing.JPanel();
        jLabelMAHeader = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMARuta = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButtonMASubir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMAArchivosEnServidor = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jButtonMADescarga = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanelCrearUsuario = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCUNombre = new javax.swing.JTextField();
        jTextFieldCUSeudonimo = new javax.swing.JTextField();
        jTextFieldCUCorreo1 = new javax.swing.JTextField();
        jTextFieldCUCorreo2 = new javax.swing.JTextField();
        jTextFieldCUTelefono = new javax.swing.JTextField();
        jDateChooserCUNacimiento = new com.toedter.calendar.JDateChooser();
        jTextFieldCUPass = new javax.swing.JTextField();
        jTextFieldCUPass2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLogin.setToolTipText("");
        jPanelLogin.setLayout(new java.awt.GridBagLayout());

        jTextfieldLoginNombre.setToolTipText("");
        jTextfieldLoginNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextfieldLoginNombreFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 237;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 79, 0, 54);
        jPanelLogin.add(jTextfieldLoginNombre, gridBagConstraints);

        jPasswordFieldLoginPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldLoginPassKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 237;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 79, 0, 54);
        jPanelLogin.add(jPasswordFieldLoginPass, gridBagConstraints);

        jCheckBoxLoginPass.setSelected(true);
        jCheckBoxLoginPass.setText("NO Visualizar caracteres");
        jCheckBoxLoginPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxLoginPassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 39, 0, 0);
        jPanelLogin.add(jCheckBoxLoginPass, gridBagConstraints);

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 39, 87, 0);
        jPanelLogin.add(jButton1, gridBagConstraints);

        jButton2.setText("Cancelar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 87, 0);
        jPanelLogin.add(jButton2, gridBagConstraints);

        jButton3.setText("Crear Usuario");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 87, 54);
        jPanelLogin.add(jButton3, gridBagConstraints);

        jTabbedPane.addTab("Inicio de Sesion", jPanelLogin);

        jLabelMAHeader.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabelMAHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMAHeader.setText("jLabel1");

        jLabel2.setText("Agregar archivos");

        jTextFieldMARuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMARutaActionPerformed(evt);
            }
        });

        jButton4.setText("...");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButtonMASubir.setText("Enviar");
        jButtonMASubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMASubirActionPerformed(evt);
            }
        });

        jListMAArchivosEnServidor.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListMAArchivosEnServidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMAArchivosEnServidorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListMAArchivosEnServidor);

        jLabel3.setText("Trabajos Subidos");

        jButtonMADescarga.setText("Descargar +");
        jButtonMADescarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMADescargaActionPerformed(evt);
            }
        });

        jButton5.setText("Cerrar Sesion");

        javax.swing.GroupLayout jPanelManejoArchivosLayout = new javax.swing.GroupLayout(jPanelManejoArchivos);
        jPanelManejoArchivos.setLayout(jPanelManejoArchivosLayout);
        jPanelManejoArchivosLayout.setHorizontalGroup(
            jPanelManejoArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelMAHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelManejoArchivosLayout.createSequentialGroup()
                .addGroup(jPanelManejoArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelManejoArchivosLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButtonMASubir))
                    .addGroup(jPanelManejoArchivosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMADescarga, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelManejoArchivosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(jPanelManejoArchivosLayout.createSequentialGroup()
                .addGroup(jPanelManejoArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelManejoArchivosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldMARuta, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelManejoArchivosLayout.setVerticalGroup(
            jPanelManejoArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelManejoArchivosLayout.createSequentialGroup()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMAHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelManejoArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMARuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMASubir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(jPanelManejoArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMADescarga))
                .addContainerGap())
        );

        jTabbedPane.addTab("Manejo de Archivos ", jPanelManejoArchivos);

        jLabel4.setText("Ingrese Nombre Personal");

        jLabel5.setText("Ingrese seudonimo");

        jLabel6.setText("Ingrese Correo ");

        jLabel7.setText("Repita Correo");

        jLabel8.setText("Ingrese Número Telefónico");

        jLabel9.setText("Ingrese Contraseña");

        jLabel10.setText("Repita su contraseña ");

        jLabel11.setText("Fecha de Nacimiento");

        jTextFieldCUTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCUTelefonoActionPerformed(evt);
            }
        });

        jDateChooserCUNacimiento.setMaxSelectableDate(new java.util.Date(946706501000L));
        jDateChooserCUNacimiento.setMinSelectableDate(new java.util.Date(-1640973499000L));
        jDateChooserCUNacimiento.setPreferredSize(new java.awt.Dimension(45, 10));

        jButton6.setText("Guardar");

        jButton7.setText("Cancelar");

        javax.swing.GroupLayout jPanelCrearUsuarioLayout = new javax.swing.GroupLayout(jPanelCrearUsuario);
        jPanelCrearUsuario.setLayout(jPanelCrearUsuarioLayout);
        jPanelCrearUsuarioLayout.setHorizontalGroup(
            jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearUsuarioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addGroup(jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldCUPass)
                        .addComponent(jTextFieldCUNombre)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCUCorreo1)
                        .addComponent(jTextFieldCUTelefono)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelCrearUsuarioLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jTextFieldCUSeudonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel11)
                        .addComponent(jLabel10)
                        .addComponent(jLabel7)
                        .addComponent(jLabel5)
                        .addComponent(jTextFieldCUCorreo2)
                        .addComponent(jTextFieldCUPass2)
                        .addComponent(jDateChooserCUNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton7))
                .addContainerGap())
        );
        jPanelCrearUsuarioLayout.setVerticalGroup(
            jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCUNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCUSeudonimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCUCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCUCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooserCUNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCUTelefono))
                .addGap(11, 11, 11)
                .addGroup(jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCUPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCUPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Crear Usuario", jPanelCrearUsuario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxLoginPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxLoginPassActionPerformed
        // TODO add your handling code here:
         if(jCheckBoxLoginPass.isSelected())jPasswordFieldLoginPass.setEchoChar('•');else jPasswordFieldLoginPass.setEchoChar((char)0);
         
    }//GEN-LAST:event_jCheckBoxLoginPassActionPerformed

    private void jPasswordFieldLoginPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldLoginPassKeyTyped
        // TODO add your handling code here:
         if(jCheckBoxLoginPass.isSelected())jPasswordFieldLoginPass.setEchoChar('•');else jPasswordFieldLoginPass.setEchoChar((char)0);

        
    }//GEN-LAST:event_jPasswordFieldLoginPassKeyTyped

    private void jTextfieldLoginNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextfieldLoginNombreFocusGained
        // TODO add your handling code here:
        System.out.println("Ingrese su contraseña personal".length()+"....."+jPasswordFieldLoginPass.getPassword().length);
        if("Ingrese su contraseña personal".length()==jPasswordFieldLoginPass.getPassword().length) {        

jPasswordFieldLoginPass.setEchoChar((char)0);    
}    
    }//GEN-LAST:event_jTextfieldLoginNombreFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       // ClienteSocket cs=new ClienteSocket(jTextfieldLoginNombre.getText(), jPasswordFieldLoginPass.getPassword());
                jTabbedPane.add("Manejo de archivos",jPanelManejoArchivos);
              //if   
       jTabbedPane.setSelectedComponent(jPanelManejoArchivos);
        jLabelMAHeader.setText("Bien venido "+jTextfieldLoginNombre.getText());
        jTabbedPane.remove(jPanelLogin);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldMARutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMARutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMARutaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        rutas();
        jTextFieldMARuta.setText(ruta);
         //cs.descargar(jListMAArchivosEnServidor.getSelectedValue(), ruta);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextFieldCUTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCUTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCUTelefonoActionPerformed

    private void jButtonMASubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMASubirActionPerformed
        // TODO add your handling code here:
        jTabbedPane.add("Inicio de Sesion",jPanelLogin);
        jTabbedPane.setSelectedComponent(jPanelLogin);
    }//GEN-LAST:event_jButtonMASubirActionPerformed

    private void jListMAArchivosEnServidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMAArchivosEnServidorMouseClicked
        // TODO add your handling code here:
        jButtonMADescarga.setText("Descarga "+jListMAArchivosEnServidor.getSelectedValue());
        System.out.println(jListMAArchivosEnServidor.getSelectedValue());
    }//GEN-LAST:event_jListMAArchivosEnServidorMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane.remove(jPanelLogin);
        jTabbedPane.add("Crear Usuario",jPanelCrearUsuario);

        jTabbedPane.setSelectedComponent(jPanelCrearUsuario);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonMADescargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMADescargaActionPerformed
        // TODO add your handling code here:
        rutas();
        
    }//GEN-LAST:event_jButtonMADescargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceLoginArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceLoginArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceLoginArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceLoginArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceLoginArchivos().setVisible(true);
            }
        });
    }
    private void rutas(){
        javax.swing.JFileChooser jF1= new javax.swing.JFileChooser(); 
ruta = ""; 
try{ 
if(jF1.showSaveDialog(null)==jF1.APPROVE_OPTION){ 
ruta = jF1.getSelectedFile().getAbsolutePath(); 
//Aqui ya tiens la ruta,,,ahora puedes crear un fichero n esa ruta y escribir lo k kieras... 
} 
}catch (Exception ex){ 
ex.printStackTrace(); 
} 

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonMADescarga;
    private javax.swing.JButton jButtonMASubir;
    private javax.swing.JCheckBox jCheckBoxLoginPass;
    private com.toedter.calendar.JDateChooser jDateChooserCUNacimiento;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMAHeader;
    private javax.swing.JList<String> jListMAArchivosEnServidor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCrearUsuario;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelManejoArchivos;
    private javax.swing.JPasswordField jPasswordFieldLoginPass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextFieldCUCorreo1;
    private javax.swing.JTextField jTextFieldCUCorreo2;
    private javax.swing.JTextField jTextFieldCUNombre;
    private javax.swing.JTextField jTextFieldCUPass;
    private javax.swing.JTextField jTextFieldCUPass2;
    private javax.swing.JTextField jTextFieldCUSeudonimo;
    private javax.swing.JTextField jTextFieldCUTelefono;
    private javax.swing.JTextField jTextFieldMARuta;
    private javax.swing.JTextField jTextfieldLoginNombre;
    // End of variables declaration//GEN-END:variables
}
